# Generated by Django 5.0 on 2024-03-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reserva', '0002_rename_id_hab_reservacion_id_habitacion'),
        ('Servicios', '0002_servicios_bar_estado_restaurante_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emitida', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.reservacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detallefactura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('producto_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicios.bar')),
                ('producto_restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicios.restaurante')),
                ('servicio_zonas_humedas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Servicios.zonashumedas')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.factura')),
            ],
        ),
    ]
