# Generated by Django 5.0 on 2024-03-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='total',
            new_name='precioServicio',
        ),
        migrations.AddField(
            model_name='factura',
            name='totalReserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(max_length=30),
        ),
    ]
