# Generated by Django 5.0.2 on 2024-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numdoc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
