# Generated by Django 5.0.2 on 2024-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_tipodocumento_customuser_idtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
