# Generated by Django 5.0 on 2024-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_alter_customuser_numdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numdoc',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
