# Generated by Django 5.0.2 on 2024-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_alter_customuser_numdoc_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='documento',
            field=models.CharField(max_length=30),
        ),
    ]
