# Generated by Django 5.0 on 2024-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_archivopdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
