# Generated by Django 5.0.2 on 2024-03-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Habitaciones', '0002_rename_id_habitacion_habitaciones_id_habitacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaentrada', models.DateField()),
                ('fechasalida', models.DateField()),
                ('cantidad_clientes', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Por Confirmar', 'Por Confirmar'), ('Confirmada', ' Confirmada'), ('Cancelada', 'Cancelada')], default='Por Confirmar', max_length=25)),
                ('id_hab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Habitaciones.habitaciones')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
