# Generated by Django 5.0.2 on 2024-03-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='id_hab',
            new_name='Id_habitacion',
        ),
    ]
