# Generated by Django 4.2.7 on 2023-11-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id_habitacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=15)),
                ('Descripción', models.CharField(max_length=50)),
                ('Espacio', models.IntegerField()),
                ('Estado', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
