# Generated by Django 4.2.7 on 2023-11-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitaciones',
            old_name='id_habitacion',
            new_name='Id_habitacion',
        ),
        migrations.RenameField(
            model_name='habitaciones',
            old_name='precio',
            new_name='Precio',
        ),
    ]
