# Generated by Django 5.0.2 on 2024-03-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0002_rename_id_habitacion_habitaciones_id_habitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoHabitaciones',
            fields=[
                ('id_tipo_hab', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Sencilla', 'Sencilla'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Suite', 'Suite')], default='Sencilla', max_length=30)),
                ('descripción', models.CharField(max_length=50)),
                ('espacio', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='Descripción',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='Espacio',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='Precio',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='Tipo',
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='id_tipo_hab',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Habitaciones.tipohabitaciones'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=30),
        ),
    ]
