# Generated by Django 5.0.2 on 2024-03-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0003_tipohabitaciones_remove_habitaciones_descripción_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipohabitaciones',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
