# Generated by Django 5.0 on 2024-03-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0004_rename_descripción_tipohabitaciones_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='is_active',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=30),
        ),
    ]
